apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1

  # purpose of the selector is to tell the deployment how to find all the pods it should make
  selector:
    matchLabels:
      app: client

  # how to create each individual pod that the deployment will make
  template:
    metadata:
      labels:
        app: client

    # how the pod will behave
    spec:
      containers:
        - name: client
          image: joesjoski/client
---
# service to go with the deployment (default service is a clusterIP)
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  # How the service finds the pods that it governs
  selector:
    app: client

  ports:
    - name: client # this name is just for logging purposes
      protocol: TCP
      port: 3000 # Next.js by default looks at this file
      targetPort: 3000
