apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1

  # purpose of the selector is to tell the deployment how to find all the pods it should make
  selector:
    matchLabels:
      app: tickets

  # how to create each individual pod that the deployment will make
  template:
    metadata:
      labels:
        app: tickets

    # how the pod will behave
    spec:
      containers:
        - name: tickets
          image: joesjoski/tickets
          env:
            - name: MONGO_URI
              value: "mongodb://tickets-mongo-srv:27017/tickets" # recall, the value after the slash refers to the database name
            - name: JWT_KEY # how it will be referenced IN THE CONTAINER
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY # what it was named IN THE KUBECTL COMMAND
---
# service to go with the deployment (default service is a clusterIP)
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
