apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # don't push to docker hub
  local:
    push: false
  artifacts:
    - image: joesjoski/auth
      context: auth # folder which contains this code
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts" # these files are synced without restarting the entire pod
            dest: . # where to sync inside the running container
